### PR TITLE
Added tool to download TAR file before RSS feeds.

### LINKED ISSUE #14: update_archive() needs to download tarball before RSS feeds
We need to download the quarterly tarball from the ThermoML Archive before updating with the RSS feeds.

Currently, only the RSS feeds are downloaded:
https://github.com/choderalab/thermopyl/blob/master/thermopyl/archivetools.py#L15

@kyleabeauchamp: Can you add this?

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Fixes #14

### CODE REVIEW

**Comment by jchodera** [comment]
There's something wrong with the resulting XML files:
https://travis-ci.org/choderalab/thermopyl/jobs/72753667#L689-L699

**Comment by kyleabeauchamp** [comment]
OK, so the new tarball changes the directory structure to be flat, as their tarballs just contain flat XML files.  Could that have killed this test?

**Comment by jchodera** [comment]
I'm not sure.  The test died at the `parse_xml` stage, so perhaps you need to update that too?

**Comment by jchodera** [comment]
OK, I think I've fixed the travis/conda stuff, but we still need you to debug what is wrong with `parse_xml` that is causing the `conda-build-pandas` script to fail.

**Comment by kyleabeauchamp** [comment]
I think this works now, but the scripts are way too slow to run on travis.  

I also pinned the version number of pyxb because it tends to not be backwards compatible.

**Comment by jchodera** [comment]
Thanks!  I'll add a test mode where it just uses a small subset of files for testing.

**Pull request merged**
