### PR TITLE
ThermoML archive rss syncing

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
```
import thermopyl
thermopyl.update_archive()
```

### CODE REVIEW

**Comment by jchodera** [comment]
Cool!

Any idea how to test this without hammering their servers?

**Comment by kyleabeauchamp** [comment]
I've just been testing locally for now, we can postpone formal tests for now because the entire RSS pipeline is still very much a work in progress.  Once Kenneth has finalized the design we can add tests that ensure the parts are working correctly.

**Comment by kyleabeauchamp** [comment]
E.g. it's possible that things might change on the TRC end of things

**Comment by jchodera** [comment]
An automated test might help alert us to when that changes, though.

What if we added a "retrieve no more than N new files when run" argument, and for testing on travis, set N = 5?   That would keep traffic low but still allow the most valuable sort of testing.

**Comment by kyleabeauchamp** [comment]
This can wait until Kenneth and I discuss any needed changes to the current
design.

**Comment by jchodera** [comment]
> This can wait until Kenneth and I discuss any needed changes to the current
design.

Sounds good!

**Pull request merged**
